---
# tasks file for install-fail2ban
- name: Install Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
- name: Ensure Fail2Ban service is enabled and started
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
...
